# Generated by Django 5.0.1 on 2024-01-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_livro', models.CharField(max_length=100)),
                ('ano_da_pub', models.CharField(max_length=100)),
                ('qtd_de_pgn', models.CharField(max_length=100)),
                ('nome_do_autor', models.CharField(max_length=100)),
                ('nome_da_editora', models.CharField(max_length=100)),
                ('preco', models.CharField(max_length=100)),
            ],
        ),
    ]
