# Generated by Django 5.0.1 on 2024-01-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='ano_da_pub',
            field=models.IntegerField(max_length=4),
        ),
        migrations.AlterField(
            model_name='livro',
            name='nome_da_editora',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='livro',
            name='nome_do_autor',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='livro',
            name='preco',
            field=models.FloatField(max_length=100),
        ),
        migrations.AlterField(
            model_name='livro',
            name='qtd_de_pgn',
            field=models.IntegerField(max_length=100),
        ),
    ]
